from typing import List, Optional
from pydantic import BaseModel
from fastapi import FastAPI
from datetime import date

app = FastAPI()

class LeaseContract(BaseModel):
    id: int
    refNo: str
    name: str
    description: str
    counterparty: str
    assetType: str
    costType: str
    isInternalTransaction: bool
    noteType: str
    leaseStartDate: str
    contractEndDate: Optional[str]
    leaseEndDate: str
    modificationDate: Optional[str]
    periodMonths: int
    monthlyFixedPayment: int
    paymentType: str
    increaseRate: Optional[float]
    increaseCycle: Optional[int]
    paymentTiming: str
    leaseStartStandard: str
    purchaseOptionPrice: Optional[int]
    depreciationPeriodMonths: int
    deposit: int
    capitalExpenditure: int
    recoveryCost: int
    impairmentDate: Optional[str]
    annualDiscountRate: float
    depositDiscountRate: float
    recoveryDiscountRate: float
    rangeChange: Optional[str]

dummy_contracts = [
  {
    "id": 1,
    "refNo": "L2023-001",
    "name": "서울 강남 사무실 임대",
    "description": "강남 테헤란로 사무실 임대 계약",
    "counterparty": "테헤란타워(주)",
    "assetType": "건물",
    "costType": "관리",
    "isInternalTransaction": False,
    "noteType": "건물",
    "leaseStartDate": "2023-10-01",
    "contractEndDate": "",
    "leaseEndDate": "2026-09-30",
    "modificationDate": None,
    "periodMonths": 36,
    "monthlyFixedPayment": 12500000,
    "paymentType": "균등",
    "increaseRate": 2,
    "increaseCycle": 12,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": None,
    "depreciationPeriodMonths": 36,
    "deposit": 100000000,
    "capitalExpenditure": 50000000,
    "recoveryCost": 10000000,
    "impairmentDate": None,
    "annualDiscountRate": 4.80,
    "depositDiscountRate": 2.94,
    "recoveryDiscountRate": 2.50,
    "rangeChange": None
  },
  {
    "id": 2,
    "refNo": "L2023-002",
    "name": "전기차 리스 계약",
    "description": "업무용 전기차 5대 리스",
    "counterparty": "현대자동차(주)",
    "assetType": "차량",
    "costType": "영업",
    "isInternalTransaction": False,
    "noteType": "차량",
    "leaseStartDate": "2023-11-01",
    "contractEndDate": "",
    "leaseEndDate": "2026-10-31",
    "modificationDate": None,
    "periodMonths": 36,
    "monthlyFixedPayment": 5000000,
    "paymentType": "균등",
    "increaseRate": None,
    "increaseCycle": None,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": 50000000,
    "depreciationPeriodMonths": 36,
    "deposit": 25000000,
    "capitalExpenditure": 0,
    "recoveryCost": 0,
    "impairmentDate": None,
    "annualDiscountRate": 4.50,
    "depositDiscountRate": 2.80,
    "recoveryDiscountRate": 2.50,
    "rangeChange": None
  },
  {
    "id": 3,
    "refNo": "L2023-003",
    "name": "데이터센터 임대",
    "description": "판교 데이터센터 임대 계약",
    "counterparty": "네이버클라우드(주)",
    "assetType": "건물",
    "costType": "IT",
    "isInternalTransaction": False,
    "noteType": "건물",
    "leaseStartDate": "2023-07-01",
    "contractEndDate": "",
    "leaseEndDate": "2028-06-30",
    "modificationDate": None,
    "periodMonths": 60,
    "monthlyFixedPayment": 45000000,
    "paymentType": "균등",
    "increaseRate": 3,
    "increaseCycle": 12,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": None,
    "depreciationPeriodMonths": 60,
    "deposit": 270000000,
    "capitalExpenditure": 100000000,
    "recoveryCost": 30000000,
    "impairmentDate": None,
    "annualDiscountRate": 4.75,
    "depositDiscountRate": 2.90,
    "recoveryDiscountRate": 2.60,
    "rangeChange": None
  },
  {
    "id": 4,
    "refNo": "L2023-004",
    "name": "물류창고 임대",
    "description": "경기도 이천 물류창고 임대",
    "counterparty": "이천로지스틱스(주)",
    "assetType": "건물",
    "costType": "물류",
    "isInternalTransaction": False,
    "noteType": "건물",
    "leaseStartDate": "2023-09-01",
    "contractEndDate": "",
    "leaseEndDate": "2028-08-31",
    "modificationDate": None,
    "periodMonths": 60,
    "monthlyFixedPayment": 35000000,
    "paymentType": "균등",
    "increaseRate": 2.5,
    "increaseCycle": 12,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": None,
    "depreciationPeriodMonths": 60,
    "deposit": 210000000,
    "capitalExpenditure": 80000000,
    "recoveryCost": 25000000,
    "impairmentDate": None,
    "annualDiscountRate": 4.60,
    "depositDiscountRate": 2.85,
    "recoveryDiscountRate": 2.55,
    "rangeChange": None
  },
  {
    "id": 5,
    "refNo": "L2023-005",
    "name": "사무용 IT장비 리스",
    "description": "노트북 및 데스크탑 200대 리스",
    "counterparty": "삼성전자(주)",
    "assetType": "비품",
    "costType": "IT",
    "isInternalTransaction": False,
    "noteType": "비품",
    "leaseStartDate": "2023-12-01",
    "contractEndDate": "",
    "leaseEndDate": "2026-11-30",
    "modificationDate": None,
    "periodMonths": 36,
    "monthlyFixedPayment": 15000000,
    "paymentType": "균등",
    "increaseRate": None,
    "increaseCycle": None,
    "paymentTiming": "후급",
    "leaseStartStandard": "월말",
    "purchaseOptionPrice": 30000000,
    "depreciationPeriodMonths": 36,
    "deposit": 45000000,
    "capitalExpenditure": 0,
    "recoveryCost": 0,
    "impairmentDate": None,
    "annualDiscountRate": 4.40,
    "depositDiscountRate": 2.75,
    "recoveryDiscountRate": 2.45,
    "rangeChange": None
  },
  {
    "id": 6,
    "refNo": "L2023-006",
    "name": "부산 지사 사무실",
    "description": "부산 센텀시티 사무실 임대",
    "counterparty": "센텀리얼티(주)",
    "assetType": "건물",
    "costType": "관리",
    "isInternalTransaction": False,
    "noteType": "건물",
    "leaseStartDate": "2024-01-01",
    "contractEndDate": "",
    "leaseEndDate": "2026-12-31",
    "modificationDate": None,
    "periodMonths": 36,
    "monthlyFixedPayment": 8500000,
    "paymentType": "균등",
    "increaseRate": 2,
    "increaseCycle": 12,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": None,
    "depreciationPeriodMonths": 36,
    "deposit": 51000000,
    "capitalExpenditure": 25000000,
    "recoveryCost": 8500000,
    "impairmentDate": None,
    "annualDiscountRate": 4.70,
    "depositDiscountRate": 2.88,
    "recoveryDiscountRate": 2.52,
    "rangeChange": None
  },
  {
    "id": 7,
    "refNo": "L2023-007",
    "name": "대전 연구소 임대",
    "description": "대전 연구개발특구 연구소 임대",
    "counterparty": "대전혁신기술(주)",
    "assetType": "건물",
    "costType": "연구개발",
    "isInternalTransaction": False,
    "noteType": "건물",
    "leaseStartDate": "2024-03-01",
    "contractEndDate": "",
    "leaseEndDate": "2029-02-28",
    "modificationDate": None,
    "periodMonths": 60,
    "monthlyFixedPayment": 25000000,
    "paymentType": "균등",
    "increaseRate": 2.5,
    "increaseCycle": 12,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": None,
    "depreciationPeriodMonths": 60,
    "deposit": 150000000,
    "capitalExpenditure": 75000000,
    "recoveryCost": 20000000,
    "impairmentDate": None,
    "annualDiscountRate": 4.65,
    "depositDiscountRate": 2.87,
    "recoveryDiscountRate": 2.53,
    "rangeChange": None
  },
  {
    "id": 8,
    "refNo": "L2023-008",
    "name": "상업용 프린터 리스",
    "description": "고성능 상업용 프린터 5대 리스",
    "counterparty": "제록스코리아(주)",
    "assetType": "비품",
    "costType": "관리",
    "isInternalTransaction": False,
    "noteType": "비품",
    "leaseStartDate": "2024-02-01",
    "contractEndDate": "",
    "leaseEndDate": "2027-01-31",
    "modificationDate": None,
    "periodMonths": 36,
    "monthlyFixedPayment": 3500000,
    "paymentType": "균등",
    "increaseRate": None,
    "increaseCycle": None,
    "paymentTiming": "후급",
    "leaseStartStandard": "월말",
    "purchaseOptionPrice": 15000000,
    "depreciationPeriodMonths": 36,
    "deposit": 10500000,
    "capitalExpenditure": 0,
    "recoveryCost": 0,
    "impairmentDate": None,
    "annualDiscountRate": 4.45,
    "depositDiscountRate": 2.78,
    "recoveryDiscountRate": 2.48,
    "rangeChange": None
  },
  {
    "id": 9,
    "refNo": "L2023-009",
    "name": "광주 지사 사무실",
    "description": "광주 상무지구 사무실 임대",
    "counterparty": "상무비즈니스(주)",
    "assetType": "건물",
    "costType": "관리",
    "isInternalTransaction": False,
    "noteType": "건물",
    "leaseStartDate": "2024-04-01",
    "contractEndDate": "",
    "leaseEndDate": "2027-03-31",
    "modificationDate": None,
    "periodMonths": 36,
    "monthlyFixedPayment": 7500000,
    "paymentType": "균등",
    "increaseRate": 2,
    "increaseCycle": 12,
    "paymentTiming": "선급",
    "leaseStartStandard": "월초",
    "purchaseOptionPrice": None,
    "depreciationPeriodMonths": 36,
    "deposit": 45000000,
    "capitalExpenditure": 22500000,
    "recoveryCost": 7500000,
    "impairmentDate": None,
    "annualDiscountRate": 4.55,
    "depositDiscountRate": 2.82,
    "recoveryDiscountRate": 2.51,
    "rangeChange": None
  },
  {
    "id": 10,
    "refNo": "L2023-010",
    "name": "서버 장비 리스",
    "description": "고성능 서버 20대 리스",
    "counterparty": "델테크놀로지스(주)",
    "assetType": "비품",
    "costType": "IT",
    "isInternalTransaction": False,
    "noteType": "비품",
    "leaseStartDate": "2024-01-15",
    "contractEndDate": "",
    "leaseEndDate": "2026-01-14",
    "modificationDate": None,
    "periodMonths": 24,
    "monthlyFixedPayment": 22000000,
    "paymentType": "균등",
    "increaseRate": None,
    "increaseCycle": None,
    "paymentTiming": "후급",
    "leaseStartStandard": "월말",
    "purchaseOptionPrice": 100000000,
    "depreciationPeriodMonths": 24,
    "deposit": 66000000,
    "capitalExpenditure": 0,
    "recoveryCost": 0,
    "impairmentDate": None,
    "annualDiscountRate": 4.35,
    "depositDiscountRate": 2.73,
    "recoveryDiscountRate": 2.47,
    "rangeChange": None
  }
]

@app.get("/api/contracts", response_model=List[LeaseContract])
async def get_contracts():
    return dummy_contracts